name: build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@master
        with:
          fetch-depth: 1
            
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      
      - name: Run Unit test
        run: make test-unit
      
      - name: Build 
        run: make build