name: publish

on:
  push:
    tags:
      - '*'
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - 
        name: Get tags
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      
      - name: build binaries
        run: make build-all
      
      - 
        name: Create SHA of binaries
        run: cd bin && ../ci/hashgen.sh && cd ../
      - 
        name: Upload binaries and their SHA to Github Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bin/kube-sync*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
